"""empty message

Revision ID: 0f5fdf60edef
Revises: 9b3096c54229
Create Date: 2019-01-11 23:56:16.273007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5fdf60edef'
down_revision = '9b3096c54229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'public')
    # ### end Alembic commands ###
