"""empty message

Revision ID: 3db5db72aca4
Revises: 0f5fdf60edef
Create Date: 2019-01-14 13:21:26.514537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db5db72aca4'
down_revision = '0f5fdf60edef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('collapse', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'collapse')
    # ### end Alembic commands ###
