"""empty message

Revision ID: 53beea9c9e2f
Revises: 3db5db72aca4
Create Date: 2019-01-14 22:43:52.014929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53beea9c9e2f'
down_revision = '3db5db72aca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('dots', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'dots')
    # ### end Alembic commands ###
